baseURL: "https://neurips-2025-site.netlify.app/"
languageCode: "en-us"
title: "Mechanistic Interpretability Workshop at NeurIPS 2025"
theme: "ananke"

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  description: "The Mechanistic Interpretability Workshop at NeurIPS 2025. How can we use the internals of neural networks to understand a model better?"
  show_reading_time: false
  
menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Schedule"
      url: "/schedule/"
      weight: 2
    - name: "Accepted Posters"
      url: "/posters/"
      weight: 3
